name: Deploy to Tailscale Server
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Tailscale
      - name: Setup Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      # Setup SSH Key
      - name: Configure Private Key and Test Connection
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Save the private key to a file
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key

          # Add the server to known_hosts
          

          # Test the SSH connection
          ssh -i ~/.ssh/private_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@100.92.35.65 "echo 'Connection Successful'"

      # Deploy code
      - name: Deploy Code to Server
        run: |
          ssh -i ~/.ssh/private_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@100.92.35.65 << 'EOF'
          cd /home/ilab/sandip/hello/server_access_task
          git checkout develop
          git pull origin develop
          cat hello.txt
          EOF
