name: Deploy to Tailscale Server
on:
 push:
   branches: [ develop ]

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     # Checkout repository
     - name: Checkout code
       uses: actions/checkout@v4
       with:
         fetch-depth: 0

     # Setup Tailscale
     - name: Tailscale
       uses: tailscale/github-action@v3
       with:
         oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
         oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
         tags: tag:ci

     # Setup SSH
     - name: Install SSH key
       uses: shimataro/ssh-key-action@v2
       with:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         known_hosts: unnecessary
         if_key_exists: replace

    #  # Add Tailscale host to known_hosts
    #  - name: Add known hosts
    #    run: ssh-keyscan -H 100.92.35.65 >> ~/.ssh/known_hosts

     # Copy repository to server
    #  - name: Copy repository
    #    uses: appleboy/scp-action@v0.1.7
    #    with:
    #      host: 100.92.35.65
    #      username: ${{ secrets.SSH_USERNAME }}
    #      key: ${{ secrets.SSH_PRIVATE_KEY }}
    #      source: "."
    #      target: "~/sandip"

     # Show contents of copied files
     - name: Display contents
       uses: appleboy/ssh-action@v1.0.3
       with:
         host: 100.92.35.65
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
           git branch
           git pull origin develop
           cat ~/hello.txt